function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
const INITIAL_CAPITAL=1000;
const NORMAL_STAKE=30;
const LATE_STAKE=10;
const LATE_MINUTE=80;
function supaConfig(){const url=process.env.SUPABASE_URL||'https://aihwrkqfzhwedqdbxbxh.supabase.co',key=process.env.SOCCERTREND_SUPABASE_SECRET_KEY;if(!key)throw new Error('Manca SOCCERTREND_SUPABASE_SECRET_KEY su Vercel');return{url,key}}
async function db(path){const{url,key}=supaConfig();const r=await fetch(`${url}/rest/v1/${path}`,{headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${text.slice(0,300)}`);return text?JSON.parse(text):null}
function entryQuote(score){const x=Math.abs(n(score));return x>=10000?(x%10000)/100:0}
function stakeFor(signal){return n(signal?.signal_minute)>=LATE_MINUTE?LATE_STAKE:NORMAL_STAKE}
module.exports=async(req,res)=>{try{const signals=await db('soccertrend_signals?message_id=lt.0&select=score,signal_minute')||[];let profit=0,wins=0,losses=0,lateEntries=0,wrong590Corrected=false;for(const s of signals){let q=entryQuote(s.score);if(!q)continue;const stake=stakeFor(s);if(!wrong590Corrected&&n(s.score)>0&&stake===30&&Math.abs(q-5.90)<0.001){q=2.75;wrong590Corrected=true}if(stake===LATE_STAKE)lateEntries++;if(n(s.score)>0){wins++;profit+=stake*(q-1)}else{losses++;profit-=stake}}const total=wins+losses,winRate=total?Math.round((wins/total)*1000)/10:0;profit=Math.round(profit*100)/100;const capital=Math.round((INITIAL_CAPITAL+profit)*100)/100;res.setHeader('Cache-Control','no-store');return res.status(200).json({success:true,wins,losses,total,winRate,initialCapital:INITIAL_CAPITAL,stake:NORMAL_STAKE,normalStake:NORMAL_STAKE,lateStake:LATE_STAKE,lateMinute:LATE_MINUTE,lateMinOdds:2.5,lateEntries,profit,capital,realEntryOdds:true,encodedWins:wins,encodedLosses:losses,source:'QUALIFIED_SETTLED_SIGNALS',wrong590Corrected})}catch(error){return res.status(500).json({success:false,error:String(error?.message||error)})}}