function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function minuteNumber(v){const m=String(v||'').match(/\d+/);return m?Number(m[0]):0}
function overMarket(h,a){return(n(h)+n(a)+.5).toFixed(1)}
function calculateScore(minute,stats,hg,ag){const corners=n(stats?.corners?.total??(n(stats?.corners?.home)+n(stats?.corners?.away))),touches=n(stats?.touchesBox?.total??(n(stats?.touchesBox?.home)+n(stats?.touchesBox?.away))),big=n(stats?.bigChances?.total??(n(stats?.bigChances?.home)+n(stats?.bigChances?.away))),shots=n(stats?.totalShots?.total??(n(stats?.totalShots?.home)+n(stats?.totalShots?.away))),sot=n(stats?.shotsOnTarget?.total??(n(stats?.shotsOnTarget?.home)+n(stats?.shotsOnTarget?.away))),pace=Math.max(25,minute||25);let score=0;score+=Math.min(24,touches*.9);score+=Math.min(20,big*6);score+=Math.min(18,corners*2.5);if(shots>0&&shots<60)score+=Math.min(12,(shots/pace*90)*.45);if(sot>0&&sot<=25)score+=Math.min(12,(sot/pace*90)*1.05);if(minute>=30&&minute<=70)score+=12;else if(minute>=25&&minute<=78)score+=9;else if(minute<=84)score+=5;else score-=8;const goals=n(hg)+n(ag);if(goals<=2)score+=6;else if(goals===3)score+=3;const activity=corners+big*2+touches/4;if(activity<3)score-=18;else if(activity>=8)score+=5;if((big>=2&&touches>=8)||(corners>=5&&touches>=10))score+=7;score=Math.max(0,Math.min(100,Math.round(score)));return{score,market:`Over ${overMarket(hg,ag)}`,corners,touches,big,shots,sot}}
function telegramConfig(){const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_CHAT_ID;if(!token||!chatId)throw new Error('Telegram env mancanti');return{token,chatId}}
async function telegramSend(text){const{token,chatId}=telegramConfig(),r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text,parse_mode:'HTML',disable_web_page_preview:true})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(`Telegram: ${JSON.stringify(d).slice(0,500)}`);return d.result}
async function telegramEdit(messageId,text){const{token,chatId}=telegramConfig(),r=await fetch(`https://api.telegram.org/bot${token}/editMessageText`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,message_id:messageId,text,parse_mode:'HTML',disable_web_page_preview:true})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(`Telegram edit: ${JSON.stringify(d).slice(0,500)}`);return d.result}
async function getJson(url){const r=await fetch(url,{cache:'no-store'}),text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error(`API ${r.status}: risposta non JSON ${text.slice(0,180)}`)}if(!r.ok||!d?.success)throw new Error(`API ${r.status}: ${JSON.stringify(d).slice(0,500)}`);return d}
function signalText(s,result=''){const resultLine=result==='WIN'?'\n\n✅ <b>WIN — GOL ARRIVATO DOPO IL SEGNALE</b>':result==='LOSS'?'\n\n❌ <b>LOSS — NESSUN ALTRO GOL</b>':'';return`🔥 <b>SOCCERTREND — SEGNALE FORTE</b>\n\n⚽ <b>${s.home} - ${s.away}</b>\n⏱ ${s.signal_minute}' | ${s.start_home_goals}-${s.start_away_goals}\n🎯 Mercato: <b>${s.market}</b>\n📊 Over Score: <b>${s.score}/100</b>\n\n🚩 Corner: <b>${s.corners}</b>\n📦 Tocchi in area: <b>${s.touches}</b>\n⭐ Big chances: <b>${s.big_chances}</b>${n(s.shots)>0?`\n🥅 Tiri: <b>${s.shots}</b>`:''}${n(s.sot)>0?` • in porta: <b>${s.sot}</b>`:''}${resultLine}\n\n🔥 <b>ADF Academy</b>`}
function supaConfig(){const url=process.env.SUPABASE_URL||'https://aihwrkqfzhwedqdbxbxh.supabase.co',key=process.env.SOCCERTREND_SUPABASE_SECRET_KEY;if(!key)throw new Error('Manca SOCCERTREND_SUPABASE_SECRET_KEY su Vercel');return{url,key}}
async function db(path,opts={}){const{url,key}=supaConfig(),r=await fetch(`${url}/rest/v1/${path}`,{...opts,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(opts.headers||{})}}),text=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${text.slice(0,400)}`);return text?JSON.parse(text):null}
async function openSignals(){return await db('soccertrend_signals?select=*')||[]}
async function claimSignal(row){try{const d=await db('soccertrend_signals',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return Array.isArray(d)&&d[0]?d[0]:row}catch(e){if(String(e.message).includes('23505')||String(e.message).includes('409'))return null;throw e}}
async function setMessageId(matchId,messageId){await db(`soccertrend_signals?match_id=eq.${encodeURIComponent(matchId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({message_id:messageId})})}
async function deleteSignal(matchId){await db(`soccertrend_signals?match_id=eq.${encodeURIComponent(matchId)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}})}
async function addResult(result){const rows=await db('soccertrend_stats?id=eq.1&select=*')||[],s=rows[0]||{wins:0,losses:0};const body=result==='WIN'?{wins:n(s.wins)+1,updated_at:new Date().toISOString()}:{losses:n(s.losses)+1,updated_at:new Date().toISOString()};await db('soccertrend_stats?id=eq.1',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});return{wins:result==='WIN'?n(s.wins)+1:n(s.wins),losses:result==='LOSS'?n(s.losses)+1:n(s.losses)}}
module.exports=async(req,res)=>{try{if(req.query?.test==='1'){await telegramSend('✅ <b>SoccerTrend Telegram attivo</b>\n\nSolo forti 78+. Una sola entrata per partita + WIN/LOSS.');return res.status(200).json({success:true,mode:'TEST'})}const protocol=(req.headers['x-forwarded-proto']||'https').split(',')[0],host=req.headers.host,base=`${protocol}://${host}`,feed=await getJson(`${base}/api/footballfree`),matches=Array.isArray(feed.liveMatches)?feed.liveMatches:[],allMatches=Array.isArray(feed.allMatches)?feed.allMatches:matches,settled=[];let existing=await openSignals();for(const sig of existing){const current=allMatches.find(m=>String(m.matchId)===String(sig.match_id));if(!current)continue;const goals=n(current.homeGoals)+n(current.awayGoals);let result='';if(goals>n(sig.start_goals))result='WIN';else if(current.finished)result='LOSS';else if(current.cancelled){await deleteSignal(sig.match_id);settled.push({id:sig.match_id,result:'VOID'});continue}if(!result)continue;if(String(sig.note||'').startsWith('SETTLED:'))continue;try{if(sig.message_id)await telegramEdit(sig.message_id,signalText(sig,result));const stats=await addResult(result);await db(`soccertrend_signals?match_id=eq.${encodeURIComponent(sig.match_id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({note:`SETTLED:${result}`})});settled.push({id:sig.match_id,result,stats})}catch(e){settled.push({id:sig.match_id,result,error:String(e?.message||e)})}}
existing=await openSignals();const candidates=matches.filter(m=>{const min=minuteNumber(m.minute);return min>=25&&min<=84}).slice(0,24),alerts=[],checked=[];for(const match of candidates){try{const id=String(match.matchId);if(existing.some(s=>String(s.match_id)===id))continue;const detail=await getJson(`${base}/api/footballfree?matchId=${encodeURIComponent(id)}`),minute=minuteNumber(match.minute||detail.minute),over=calculateScore(minute,detail.stats||{},match.homeGoals,match.awayGoals);checked.push({id,match:`${match.home} - ${match.away}`,minute,score:over.score,market:over.market});if(over.score<78)continue;const row={match_id:id,message_id:null,home:match.home,away:match.away,start_home_goals:n(match.homeGoals),start_away_goals:n(match.awayGoals),start_goals:n(match.homeGoals)+n(match.awayGoals),signal_minute:minute,market:over.market,score:over.score,corners:over.corners,touches:over.touches,big_chances:over.big,shots:over.shots,sot:over.sot};const claimed=await claimSignal(row);if(!claimed)continue;try{const sent=await telegramSend(signalText(row));await setMessageId(id,sent.message_id);alerts.push({id,score:over.score,market:over.market,match:`${match.home} - ${match.away}`})}catch(e){await deleteSignal(id);throw e}}catch(error){checked.push({id:match.matchId,error:String(error?.message||error)})}}const statsRows=await db('soccertrend_stats?id=eq.1&select=wins,losses')||[];return res.status(200).json({success:true,mode:'STRONG_ONE_ENTRY_V6',telegramThreshold:78,live:matches.length,candidates:candidates.length,alerts,settled,openSignals:(await openSignals()).length,stats:statsRows[0]||{wins:0,losses:0},checked})}catch(error){return res.status(500).json({success:false,error:String(error?.message||error)})}}